---



- hosts: clara
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    container_image: "mercury/rstudio-clara:v1.0" 
    rstudio_password: "1234"
    rstudio_port: "80"
  tasks:
    # - name: Wait for automatic system updates
    #   become: yes
    #   shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
    #   with_items:
    #     - lock
    #     - lock-frontend
    # - name: Install aptitude using apt
    #   apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
     
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes 
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      until: apt_status is success
      register: apt_status
      delay: 60
      retries: 10

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
     

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
  

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest


    - name: Install Docker Module for Python
      pip:
        executable: pip3
        name: docker
   
    - name: creates a directory on which the volume would be mounted
      mount:
        path: /home/ubuntu/disk
        src: /dev/vdb 
        state: mounted
        fstype: ext4

    - name: run a docker container
      docker_container:
        name: rstudio
        image: "{{ container_image }}"
        state: started
        restart: yes
        env: 
          PASSWORD: "{{ rstudio_password }}"
        volumes:
          - /home/ubuntu/disk:/home/rstudio/data
        ports:
          - "{{ rstudio_port }}:8787"


